### PR TITLE
Final Project V.1

### PR DESCRIPTION
**Pull request by ryby6969**

### CODE REVIEW

**Comment by ryby6969** [comment]
Please let me know if it works on your computer and what you think I can change to make it better. I was looking for some art to use for the answers but didn't find anything I liked.

**Comment by xyngabo** [comment]
I ran it on my computer and initially it gave me an indent error, likely because you uploaded it as a text file.  After fixing that though, it ran perfectly.. Good Job! =)

**Comment by xyngabo** [comment]
If you are still looking for art, I just googled ascii art and found several sites with a ton of different types of 'art' to choose from.

**Comment by chrispelaez** [comment]
line 10 of your code has the indent error other than that the program runs smoothly

**Comment by BobbyGatlin** [comment]
Other than the indent error, everything works just fine.

**Comment by ryby6969** [comment]
Thank you everyone, I will fix the indent error and see if I can find some art I like also.

**Comment by halfaro1** [comment]
@ryby6969 good start. Please use functions as it has been utilized in all projects until now and it's a best practice.

Additionally, you should modify the design document and add a little information about the structure behind the scenes of your program.

I'd also suggest changing the file extension to `.py` to match a Python extension. 

Because of the relatively simple complexity of the game, if I could suggest, you can add a verification that the user ended their question with a `?` mark to ensure they've typed a question.

Linking this open request to your proposal so it closes #4

**Comment by Chummel** [comment]
I really enjoyed this. I ran it through a bunch of questions and every time it worked. Great project!

**Comment by imiller6** [comment]
Worked great on my end. Great project.

**Comment by ryby6969** [comment]
I cannot figure out how to add a verification for a ? at the end of the question. I tried the in or not in but it seems to only work for lists or tuples.

**Comment by ryby6969** [comment]
Nevermind, I figured that part out.

**Comment by halfaro1** [comment]
@ryby6969 great thanks for your improvements. How about that design document? Especially in a project relatively straightforward like yours, I'd like to see a good, thorough design document that explains how your code is structured, how the different parts of your code interact with one another, how the question mark is found, and so on.

**Comment by halfaro1** [comment]
@ryby6969 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
