### PR TITLE
Nathan Spencer Final Project

### PR DESCRIPTION
**Pull request by Nate388**

### CODE REVIEW

**Comment by halfaro1** [comment]
@Nate388 gave you some feedback on Gitter, but to summarize it, make sure you're using functions and add a design document.

Linking to your proposal so it closes #37

**Comment by aeuteneuer** [comment]
Hello Nathan,

I enjoyed this game I thought it was very clever.  I do recommend maybe adding a runner file like the professor has has in previous assignments because it makes the code easier to run for others.  I also think there should be a check to see if the user types in something different then the two choices it is listening to.  Typing a typo would stop this program.  Other than that I enjoyed the story. Great job.

**Comment by larawillson** [comment]
This was such a cool and clever idea Nate. The program was very easy to run. I think the one change I would make is if a user types in an answer that does not work with the two options, then it should prompt the user again to choose between the options, instead of just continuing on... Just a thought... but overall this is super creative, great job!

**Comment by Nate388** [comment]
@aeuteneuer, @larawillson. I know. One of the big things I thought about from the beginning was what if the player didn't chose an option. I was very rushed for time. But thanks for the feedback! I hope you enjoyed it.

**Comment by AustinBarnett** [comment]
Overall great work, Like the above comment I would reccomend not allowing it to just continue on if not chosen. Great work overall!

**Comment by Tchomp** [comment]
Just reading this project was somewhat fun. I not only enjoyed the dialogue but found it making me wish to read more like a story. That run or gun choice where you have to decide and how it affects the long-run shows a knowledge for keeping track of the general code which I can appreciate. Hope this leads to creating more clever and brilliant ideas!

**Comment by halfaro1** [comment]
@Nate388 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
