### PR TITLE
Commit 1

### PR DESCRIPTION
**Pull request by EvanLuke**

### CODE REVIEW

**Comment by Nate388** [comment]
I ran it several times because I was actually having too much fun. I love how complex your code looks. I could spend a while asking questions about how things run together. I think something that your program could benefit from would be the ability to print the letters you've already used each new turn. But really amazing. Great job! :sparkles:

**Comment by EvanLuke** [comment]
@Nate388 Hey thanks! You are right, I added some code so now it will show all of the letters you have used so you can keep track.

**Comment by pvo4** [comment]
Great job with the program and the update. I played the 1st commit and was thinking the same thing as Nate. It really came in handy having a used word bank. However the word list is a little small. Maybe you can have the program grab words from a bigger database like a dictionary or book, that way you don't have to go in and write out a list of words every time. Also, it will make the game more difficult.

**Comment by elisenharper** [comment]
That was really fun! I like how you incorporated a used letter bank.

**Comment by halfaro1** [comment]
@EvanLuke I'd like to test your program but I see multiple files, and the `README` doesn't tell me which one to use. Could you include only one file and make the directions specific on your `README`? So far though I like what I'm seeing from just glancing at it :)

**Comment by EvanLuke** [comment]
@halfaro1 I reuploaded with less files. @elisenharper Thank you! @pvo4 Yes that would be a good addition, it could even have different difficulties to set it to from beginner words to advanced.

**Comment by halfaro1** [comment]
@EvanLuke awesome -- great improvements. If you're reaching for maximum points, I suggest fleshing out your design document a little further.

**Comment by halfaro1** [comment]
@EvanLuke I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
