### PR TITLE
SA Final Project Sub 1

### PR DESCRIPTION
**Pull request by sabbott7**
@halfaro1  and class have I missed anything ?

### CODE REVIEW

**Comment by sabbott7** [comment]
@halfaro1 have I missed anything ?

**Comment by gkaja14** [comment]
It worked in my computer. Its a cool game. I enjoyed playing it.

**Comment by xyngabo** [comment]
It works on my computer too and I have lost twice so far.

**Comment by sabbott7** [comment]
Your welcome @gkaja14 ...

**Comment by sabbott7** [comment]
Thankyou @xyngabo for your feedback...It get's very addictive after awhile

**Comment by ngocnguyen83** [comment]
:star: I love it but I lost all the game  :cry:  Works well on my computer :yum:

**Comment by sabbott7** [comment]
Thank you @ngocnguyen83 kindly for your feedback...I'll consider increasing the number of turns to make it not so harsh..

**Comment by BobbyGatlin** [comment]
Yeah. increasing the turn number would be the only thing I suggest. I love the implementation though. It worked really well but I couldn't win

**Comment by sabbott7** [comment]
Thanks for your feedback @BobbyGatlin on my last commit have increased number of turns to 10 !!

**Comment by halfaro1** [comment]
@sabbott7 such an awesome project -- thanks for sharing!

Regarding your design file, can we see a little bit about the behind-the-scenes structure of your program? How is information structured in the program? How is the location of the battleship generated? 

Regarding the README file, I see some instructions that mentions q1 and q2 but there are no files that are called that in your project.

Just adding a reference to the issue so that we can close this pull request it automatically closes #10

**Comment by rtran4** [comment]
Works great on my mac! I always lose to your program, but I am determined to win haha. It's great though, good job!

**Comment by sabbott7** [comment]
@rtran4 Thanks for your feedback. That's the spirit, never say die ! :-)

**Comment by sabbott7** [comment]
@halfaro1 I have updated the files as suggested. Including detail like program structure, how the battleship is located, program flow and a "to run" instruction in the readme.

**Comment by elisenharper** [comment]
This is really cool! It ran well on my computer the only thing is it just shut down when I lost

**Comment by sabbott7** [comment]
@elisenharper Thanks for the feedback. I'm glad you enjoyed it. Did you use idle to run the program or  something else ?

**Comment by halfaro1** [comment]
@sabbott7 Fantastic work 👍 
Closing this out as it's now complete. Your grade is on Blackboard.

**Pull request closed without merging**
