### PR TITLE
Final Project Jarvis #1 

### PR DESCRIPTION
**Pull request by nickivey2**

### CODE REVIEW

**Comment by halfaro1** [comment]
@nickivey2 I don't see instructions in the `README` file in `devel`. It seems like we need to install some modules/libraries to get your code running? Also make sure you're adding a design document that explains the logic behind your code.

**Comment by nickivey2** [comment]
I have uploaded my submission of Jarvis

**Comment by aeuteneuer** [comment]
Hello Nick,

I tried to run your program and the first pip (PyAudio==0.2.9) threw me an error while trying to download.  Perhaps the pip is outdated?  If I did get this application running correctly however I must say this is very impressive. I like how you tried to replicate an AI technology. Great job!

**Comment by halfaro1** [comment]
@nickivey2 I'm having the same issue as @aeuteneuer :
```
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/v0/1fszrshn2z5bhw6mx35d4p080000gp/T/pip-build-70ti2gl7/PyAudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/v0/1fszrshn2z5bhw6mx35d4p080000gp/T/pip-6u9j9ce6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/v0/1fszrshn2z5bhw6mx35d4p080000gp/T/pip-build-70ti2gl7/PyAudio/
```

**Comment by halfaro1** [comment]
@nickivey2 I should also mention that if we can't get the right libraries loaded it's not the end of the world, but if you still want to make sure you get the highest number of points possible, flesh out your design document a little more. Especially with the complexity of your project in particular, we'd all benefit from knowing how you did your project (even more so if we can't run it)

**Comment by halfaro1** [comment]
@nickivey2 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
