### PR TITLE
Playing Madlibs

### PR DESCRIPTION
**Pull request by larawillson**
@halfaro1 Sorry for the delay :( I've been sick with the flu for the last week, so I've been very limited in time to work on this.

### CODE REVIEW

**Comment by rtran4** [comment]
Your program is really detailed! I love how there are 4 stories and it's long and entertaining for the user! Great job!

**Comment by Nate388** [comment]
I really loved playing this. I caught myself laughing out loud a couple times too. I love how detailed and finished the project is. During the story telling parts some words didn't fit on the screen and had to be moved to the next line to read. You could fix this by adding `\n` right before where the words cut off to bump them to the next line. But great work! :sparkles:

**Comment by pvo4** [comment]
Great program, I couldn't help but chuckle a bit too. There were a couple words that weren't concatenated right so it combined the input with one of the other words in the story. Other than that, wonderful job!

**Comment by AustinBarnett** [comment]
Very long program but I am very happy I stood with it and surprised on how it all came together! Very impressed on the different options and re usability of the program! Great job!

**Comment by elisenharper** [comment]
What a great idea for a project!

**Comment by halfaro1** [comment]
@larawillson I will echo what other classmates are saying and let you know you've done a great job! I want to give you a few tips to make sure you get 💯 

1. A design document is needed as part of the submission. That design can include part of the discussion that went on during the proposal, and should include an explanation of how your code is structured (a look  behind the scenes) and maybe some diagrams or pseudocode.
2. The program should use functions -- functions are a core part of learning how to program and they were utilized throughout the entire course.

I'm linking to your proposal so that when we close this pull request it will also close #27

**Comment by halfaro1** [comment]
@larawillson I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
