### PR TITLE
Project So Far

### PR DESCRIPTION
**Pull request by LuisDavilaBermudez**
This is the program so far.

### CODE REVIEW

**Comment by halfaro1** [comment]
@LuisDavilaBermudez could you provide some sample images that you're using to test your program? Also don't forget a design document that explains the logic behind the program.

**Comment by halfaro1** [comment]
@LuisDavilaBermudez I noticed your proposal is still open, please finalize that before moving forward

**Comment by LuisDavilaBermudez** [comment]
How would I close it

**Comment by halfaro1** [comment]
@LuisDavilaBermudez I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
