### PR TITLE
Completed final project

### PR DESCRIPTION
**Pull request by Ldesir05**
due to the long process of me getting an approval
didn’t get to post a first draft so here is my final draft. Please give me some feed back

### CODE REVIEW

**Comment by Ldesir05** [comment]
Has anyone tried my code ???

**Comment by halfaro1** [comment]
@Ldesir05 I did ✋! Looks pretty neat. Please try to give some structure to your code by using at least a couple of functions, and include a design document. We did a lot of the design work on your proposal but that needs to be documented in a document. 

Linking to your proposal so it closes #15

**Comment by nickivey2** [comment]
I tried it worked great for me. I have done something similar in C# in the past working on consolidating payroll hours. Excel sheets are a pain to work with, if you are continuing working on it I would go ahead and save the data to a xml file or something that you could easily sync to a Data Table View.

**Comment by EvanLuke** [comment]
It wouldn't run first try on my computer, it returned: 
Traceback (most recent call last):
  File "C:/Users/Evan/AppData/Local/Programs/Python/Python35/final111.py", line 4, in <module>
    from openpyxl import Workbook
ImportError: No module named 'openpyxl'

**Comment by jnoriega3** [comment]
I am getting a similar error as well:
Traceback (most recent call last):
  File "C:\Users\norij811\AppData\Local\Programs\Python\Python35-32\pip install selenium design document.py", line 4, in <module>
    from openpyxl import Workbook
ImportError: No module named 'openpyxl'

**Comment by Ldesir05** [comment]
@jnoriega3 you need to install the openpyxl by using pip install openpyxl in command prompt on windows and on osx use terminal

**Comment by halfaro1** [comment]
@jnoriega3 and @EvanLuke -- follow @Ldesir05's `README` file to install openpyxl and selenium before running his code.

@Ldesir05 have you looked through [my suggestions](https://github.com/valencia-cop1000-201620/final-project/pull/74#issuecomment-215072853)?

**Comment by Ldesir05** [comment]
@halfaro1 
i have added a design document

**Comment by halfaro1** [comment]
@Ldesir05 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
