### PR TITLE
Final Project First Shot

### PR DESCRIPTION
**Pull request by cholbrook2**

### CODE REVIEW

**Comment by xyngabo** [comment]
Works on my computer. I like how it restarts if you type in an unknown.

**Comment by ngocnguyen83** [comment]
Wow... really interesting! :sparkles:  It works well on my laptop as well.

**Comment by BobbyGatlin** [comment]
Worked well. It's pretty simple. I  see how it could help you figure out where to eat.

**Comment by ryby6969** [comment]
Very nice. Buca di Bepo is as far as I needed to go. LOVE that place.

**Comment by smoussadeq** [comment]
Worked well on my computer. Great work! There is nothing I think you should add or modify.

**Comment by cholbrook2** [comment]
Thank you, everyone!

I agree @ryby6969 Buca is awesome!!

**Comment by halfaro1** [comment]
@cholbrook2 good start! I have a few suggestions.

First, I'd suggest using functions as it's a best practice that we've followed all semester.

I also suggest you follow your proposal and allow the user to enter their zip code and search by zip code. To do this, you'll need to have a sense of the acceptable zip codes and give the user some options. At least that way there's a two-way selection (1) location and (2) type of food. 

I'm linking this to the proposal so when we close this it will close #7

**Comment by cholbrook2** [comment]
@halfaro1 alright! I gave it a go. I played around a bit more with the functions, but that was a weaker point of mine.

**Comment by halfaro1** [comment]
@cholbrook2 Awesome! I'll let the class chime in to see if it works on their computers. How about a design document? It can include some of the work you did to find the restaurants, but also an explanation of your code does its work.

**Comment by elisenharper** [comment]
@cholbrook2 Very fun! I think this would solve a lot of couple debates :) Is there anyway to incorporate the address into the program? Rather than suggesting the restaurant and then having to look it up? Just a suggestion. I think it's really cool other than that!

**Comment by halfaro1** [comment]
@cholbrook2 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
