### PR TITLE
Final Project: Blackjack

### PR DESCRIPTION
**Pull request by pvo4**
This is a working program of the game blackjack. After some research on the best way to create a game of blackjack, the conclusion was to use OOP or object-oriented programming. I spent the past couple of days reading and trying to understand the concepts of OOP. The following program utilizes a lot of the basics we've learned and employs a few new ideas. Basically, I created classes that define an object and holds characteristics along with behaviors for the object. I can then call upon the object or use it in other classes. The game works as is, but is missing a feature that allows betting. Also, I wanted to add some cosmetic features to the game like a better title. I know this pull request is late, but I'm open to any feedback. I'll be working on the program until the deadline.

Game Example:
 
How many players? (1 - 2): 1
Enter player name: phil

phil:	5D	6C	(11)                                   #5D (5 of Diamonds) +  6C (6 of Clubs)  =  (11)
Dealer:	XX	2H	                                 #XX = Dealer's Face Down Card 

phil, do you want a hit? (Y/N): 

phil, do you want a hit? (Y/N): y
phil:	5D	6C	QH	(21)

phil, do you want a hit? (Y/N): n
Dealer:	JH	2H	(12)        #Dealer's second card is reveal on dealer's turn, XX = JH (Jack or Hearts)
Dealer:	JH	2H	10D	(22)                   
Dealer busts.
phil wins.

Feedback:

-   What can I improve upon?

-  Is the program messy?

-  What I did wrong?

-  Your thoughts on the game?

-  Etc

### CODE REVIEW

**Comment by rtran4** [comment]
Hey this is really cool! I just play it a few times and love how your program adds up the numbers for you. It's really easy to use. I didn't understand the letters, but it's great!

**Comment by AustinBarnett** [comment]
I think your understanding of the game was really helpful in building the program and I love how simple working the game was.

**Comment by halfaro1** [comment]
Great work so far, @pvo4. I'm also seeing great positive feedback from your classmates :)

The only thing I see that's missing is a design document that explains your code, your logic, and possibly some diagrams or pseudocode. Part of what we discussed in your proposal can go into the design document. I also think the design document is a fantastic place to point out any references that you used on the web to help you get your program started (that is OK and allowed, but let's give credit).

I'm linking to your proposal so that when we close this pull request it will also close #14

**Comment by EvanLuke** [comment]
Awesome game, I didn't even think of making a program for a card game. Awesome idea.

**Comment by EvanLuke** [comment]
I think it is incredible that after one semester of programming we are making games such as these. Programming has been the most fun I have had in a class in a long time. It feels so good to build something.

**Comment by halfaro1** [comment]
Fantastic work, @pvo4 👍 

Your final grade is on Blackboard.

**Pull request closed without merging**
