### PR TITLE
Commit 1

### PR DESCRIPTION
**Pull request by BobbyGatlin**
Hope you enjoy :)

### CODE REVIEW

**Comment by cholbrook2** [comment]
I LOVE THIS! The Evil Dead movies are amazing! When I ran the program through Windows, it shut down before I could read the end passage, though... On IDLE, it worked perfectly fine :)

**Comment by BobbyGatlin** [comment]
#halfaro and class. This is ready to be looked over. I'm pretty proud of it. :)

**Comment by MarcialSegura** [comment]
Hey @BobbyGatlin  just played your game and I had some fun it. Great work! The only thing I could be picky with is the map. I noticed that the house is orientated in a way that perhaps someone can look at it and not know which way points North or South. An easy fix is throw in a compass, so that way the player can have a sense of direction and not lose their orientation. I didn't have that issue while playing but like I said that's me being picky, other than that your code was fine I didn't run into any issues.

**Comment by xyngabo** [comment]
I love this, for both the movie you chose and the idea itself.  It reminds me of the early 90's when stories done in this manner was kind of popular.  I had a fun version of Hitchhiker's Guide to the galaxy, that someone had made.  Good job =)

**Comment by Lamle104** [comment]
Great project! Made me feel as if I were at halloween horror nights or something haha.

**Comment by halfaro1** [comment]
@BobbyGatlin awesome work, pretty fun game. I appreciated your use of functions 👍 

Is there an end to the game? I never did get to it, but I did a pretty quick run-through.

You will need to fill out your design a little more. You can use some of the development from your proposal to help you. Your design should explain a bit about the logic behind your code and the data structures you chose to design. 

Linking this open pull request to your proposal so it closes #12

**Comment by Chummel** [comment]
I really enjoyed this game! I can tell it took a lot of work and it shows, it was incredibly well put together!

**Comment by BobbyGatlin** [comment]
Yeah there definitely is an end. You just have to find the Necronomicon that's hidden randomly in one of the rooms and get back to the Living Room. I added #comments to my PY file in the design folder to give you a little more intel on how I chose my coding. This was a super fun project and I thoroughly enjoyed creating this game.

**Comment by halfaro1** [comment]
@BobbyGatlin awesome. If you'd like to try and get the maximum possible points, I'd keep your comments as part of the python file, but I'd create a separate design document with a narrative explaining how your code works. Comments are good but they should already be in your code. A design document explains in detail how your code achieves what it does. It could even give us a glimpse at how the project changed from inception during the proposal, to its final execution.

**Comment by halfaro1** [comment]
@BobbyGatlin I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
