### PR TITLE
final project

### PR DESCRIPTION
**Pull request by gkaja14**

### CODE REVIEW

**Comment by xyngabo** [comment]
FYI.  You copy and pasted your python code to the read me file.  The read me file is supposed to contain instructions on how to use your script.

**Comment by gkaja14** [comment]
@xyngabo Thanks a lot for the info. I just add my .py file to the dlevel folder.

**Comment by xyngabo** [comment]
When I run this on my computer, I get a syntax error on the line: guess = int(input())

**Comment by gkaja14** [comment]
@xyngabo I fixed it now, lmk if you still get any errors. Thanks for your help!

**Comment by chrispelaez** [comment]
your game is like the dark souls of number guessing games. I tried 5 times with no issues. 10/10 will rage quit this game but it is fun.

**Comment by halfaro1** [comment]
Thanks for sharing @gkaja14! It's so fun to see these go from ideas into implementation.

I ran into trouble with your program. For example, I started guessing `120` and it told me `pico`, which means one digit is not in the correct place. So I tried `210` and it said `bagels` which means no digits are in the correct place, however, since `210` is the same digits but in different order it should at least say another `pico`, if not `fermi`, correct?

Additionally, I'm not seeing anything for your design, did you create a design document?

I'm linking this to your issue so that when we close this it closes #18

**Comment by Chummel** [comment]
Really interesting and fun program. I liked the ingenuity behind it and I thought it was very well put together. I didn't find any problems

**Comment by gkaja14** [comment]
@halfaro1 I fixed some of them, let me know if it works now.

**Comment by halfaro1** [comment]
@gkaja14 what about your design document?

**Comment by halfaro1** [comment]
@gkaja14 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
