### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by smoussadeq**

### CODE REVIEW

**Comment by smoussadeq** [comment]
@halfaro1 Done!!!
Hello Classmates!
Does the run well on your computer?
Is there something I should add or modify?

**Comment by shuroq** [comment]
Hello, I ran your code on my computer and it is working. Everything is clear and simple. Great work

**Comment by halfaro1** [comment]
@smoussadeq great work so far. I will suggest that you use functions as that has been a required component of all projects up to now. Additionally, don't forget to include a design document that contains the logic behind your code. 

Linking to your proposal so it closes #29

**Comment by smoussadeq** [comment]
@halfaro1 I started my project from scratch and added functions. I also included a design document.

**Comment by halfaro1** [comment]
@smoussadeq awesome, we are 👍 on the functions. The design document is still not there though. The design document should allow you to explain to someone how your code works behind the scenes. You can do so with words (like a written explanation) or diagrams (a flowchart) or pseudocode (a rough structure of your program).

**Comment by smoussadeq** [comment]
@halfaro1 I already added a picture of my program #29 
Also, for some reason week 3 &14 are still not graded.
Thank you for your time!

**Comment by MarcialSegura** [comment]
Programed worked fine for me, Nice work!

**Comment by halfaro1** [comment]
@smoussadeq a design document is a narrative that talks about your code. Pictures are welcomed, but aren't enough to constitute a design document. In a separate file, as part of your project, please add a design file where you can write about how your code works, how your functions are structured, how your code changed from inception to execution, etc. 

Regarding ungraded projects, please reach me privately via Gitter or email.

**Comment by smoussadeq** [comment]
@halfaro1 I added a word document that explains how my code works and everything needed for the assignment. Thank you for your help not only this time but during the whole semester!

**Comment by halfaro1** [comment]
@smoussadeq I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
