### PR TITLE
Final Project - Currency Converter

### PR DESCRIPTION
**Pull request by DanielCowman**

### CODE REVIEW

**Comment by xyngabo** [comment]
Easy to understand and it works well on my computer. Good job =)

**Comment by ryby6969** [comment]
Pretty useful program you have. I like it.

**Comment by smoussadeq** [comment]
👍 Worked well on my computer. Great work! There is nothing I think you should add or modify.

**Comment by DanielCowman** [comment]
Thank you all for the feedback, I went ahead and cleaned up the code a little in main.py and implemented a runner file for added UX

**Comment by halfaro1** [comment]
@DanielCowman great work so far! I ❤️ that you took on the challenge of using an API and you did it with flying colors 🌈 

 I did need to install the `requests` library so that should be in your `README`. Additionally, I noticed your program rounded to the nearest dollar, is that on purpose?

Also, please include a design document that explains the logic behind your code.

Adding a link to your proposal so that when we close this pull request it closes #26

**Comment by larawillson** [comment]
Awesome Job Daniel. Ran without a hitch on my computer. This program could be so to people who work a lot in finances etc.!

**Comment by DanielCowman** [comment]
@halfaro1, @larawillson: Thank you for the feedback!

halfaro1: I've altered the way the converted_currency variable was returned it should now return to the nearest hundredth, I've removed the readme as it was not aesthetically pleasing and created a design doc which documents everything you need to know about the currency converted.

**Comment by halfaro1** [comment]
@DanielCowman I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
