### PR TITLE
FileScanner V.1

### PR DESCRIPTION
**Pull request by mmarchetti2**
I've added files to the design folder, which contains some info on the
formats to scan for. Also, I've added working code to the devel folder,
I'll try to add more features.

### CODE REVIEW

**Comment by mmarchetti2** [comment]
So far, I have a phone number and code scanner that can check pdf and txt files. :) I'm almost absolutely sure I can get the times feature implemented on time, so I'll start thinking of a fourth setting.

**Comment by mmarchetti2** [comment]
Oh, I just realized that I should add how to install PyPDF2. I'll add that to the instructions file when I complete the time setting.

**Comment by sabbott7** [comment]
thanks for confirming the phone number forms in your instructions.

**Comment by mmarchetti2** [comment]
Okay, there we go. I've added the times setting, condensed the phone regexes, added the instructions to install PyPDF2, and some other minor stuff. :) I think it's ready, @halfaro1

**Comment by halfaro1** [comment]
@mmarchetti2 can you share a file you are using to test against? 

Linking this to your proposal so this pull request closes #11

**Comment by mmarchetti2** [comment]
Okay, there we go. I shared the file I'm using to test, and I fixed a few things here and there.

**Comment by halfaro1** [comment]
All that's missing is a little fleshing out of your design document so your classmates and I can get a peek at how your program works. Might want to explain some of what we discussed in your proposal as well as how your regex's work.

i m amazed this didn t already exist may i present to you the matthew mcconaughey alright alright alright gif - imgur

**Comment by nickivey2** [comment]
Great tool, using a program like this in a email client would be extremely helpful.

**Comment by mmarchetti2** [comment]
There we go, I added a couple of info files to the design folder, so now there's more information about the program. :)

**Comment by halfaro1** [comment]
@mmarchetti2 fantastic work ✨ 👍 

Closing this out. Your grade is found on Blackboard.

**Pull request closed without merging**
