### PR TITLE
Bestfriend similator (unfinished)

### PR DESCRIPTION
**Pull request by digitalBeast**
Having some trouble on creating another response choice after the if
statement. PLEASE I need help, email me or send feedback on the project i am working on. I'll be open all day until 6 pm and be back at 7:30 or 8. 
The program runs smoothly it just that, I couldn't come up with a method to take the 'COMPUTER' response to make the user take a choice to answer back.

### CODE REVIEW

**Comment by Ldesir05** [comment]
@digitalBeast  i tried you code and noticed that i couldn't input my response. if you want the user to enter an answer you should use the input() . you can also try assign the answers to number for example 
1 = ok 
2 = good
3 = bad
then ask the user to choose a number just a thought

**Comment by halfaro1** [comment]
@digitalBeast make sure you're also using functions as we've used in the course previously.

**Comment by nickivey2** [comment]
This is great, I like it. To bring the program to life you could use Speech Recognition and Text to speech to have the program say the responses to you.

**Comment by halfaro1** [comment]
@digitalBeast thanks for the design document! if you're reaching for maximum score, you'll also need to include functions

**Comment by digitalBeast** [comment]
functions in the design document

**Comment by ukates** [comment]
@digitalBeast Very cool! It almost feels like i really have a friend when i run the program.  It may be getting a lot of use out of me when my girlfriend is mad i didn't take out the garbage, give me someone to talk to .  I love how the computer tries to cheer me up!

**Comment by halfaro1** [comment]
@digitalBeast I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
