### PR TITLE
Final project-Joseph Gonzalez

### PR DESCRIPTION
**Pull request by JoetheJedi**

### CODE REVIEW

**Comment by halfaro1** [comment]
@JoetheJedi 👍 great use of functions and overall a ✨ program.

All that's missing is a design document to explain your logic and tie it all together. 

Linking to your proposal so it closes #28

**Comment by halfaro1** [comment]
@JoetheJedi I also noticed your proposal is still open. Please finalize that before moving forward.

**Comment by JoetheJedi** [comment]
@halfaro1 how do i finalize it?

**Comment by halfaro1** [comment]
@JoetheJedi just waiting on your design document

**Comment by halfaro1** [comment]
@JoetheJedi I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Comment by JoetheJedi** [comment]
@halfaro1 thanks so much for allowing me to make up those assignments. I thought i was a goner 3 weeks ago. Enjoy your summer as well!

**Pull request closed without merging**
