### PR TITLE
Final

### PR DESCRIPTION
**Pull request by Chummel**

### CODE REVIEW

**Comment by Chummel** [comment]
Hopefully nothing goes wrong with it. If anyone finds any errors in the program please let me know!

**Comment by JoetheJedi** [comment]
Hey @Chummel! I think the program is great! One thing i noticed is if the user types in "n" instead of "N" the program stops working. You could possibly use a "while True" statement to loop until the user inputs the correct options "Y" or "N"!

**Comment by imiller6** [comment]
Nice project, worked fine on my computer. It said I should be a computer programmer! Glad I took the right class.

**Comment by Ldesir05** [comment]
@Chummel 
 this is a great code at first i was thinking is there a way to use less if statements and i agree with what @JoetheJedi said .

**Comment by elisenharper** [comment]
I have a question about running the file. Do I save it to my computer? Or is there a way to run it in Python without downloading it? Sorry I'm new to all this

**Comment by halfaro1** [comment]
@Chummel good start. Your program needs to use functions like we've used in other projects in the course. Please make sure you do that. 

Additionally, you should probably change the extension of your file so it's a Python extension `.py`. 

Linking to your proposal so it closes #30

**Comment by MarcialSegura** [comment]
Nice! said I should be a Programmer, good work!

**Comment by halfaro1** [comment]
@Chummel I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
