### PR TITLE
Card Game War- Elice Greenberg Final Project

### PR DESCRIPTION
**Pull request by elicegreen**

### CODE REVIEW

**Comment by elicegreen** [comment]
I did it!!! Took me hours, but I did it! The one thing I struggled with most is figuring out how to code the game in situations of multiple 'wars' in a row, but finally, after many trials and errors and some online visual coding tools, I finally figured it out! 
I have actually exceeded my own expectations! I felt comfortable with simplifying the original game when I first started planning how to code this, but ended up figuring out how to code it to be played in it's original form :-) I also ended up incorporating dictionaries, even though I didn't think I would, as I thought I would just stick with lists. The dictionary makes the game more user friendly and easier for the player to understand, as it better simulates real cards.
And I even finished coding one day earlier than I had given myself in my timeline planning!

Please let me know if any issues arise as soon as possible so I can attend to them! 
I will be on a plane to Colombia this coming Wed to see my sister whom I haven't seen in over three years! I want to make sure I am done with everything by then. Thank you! :-D

**Comment by chrispelaez** [comment]
war...war never changes. Very nice game homie it runs well and is fun to play. Ran through 2 games with no issues

**Comment by elicegreen** [comment]
Thank you @chrispelaez :-)
Can you please advise me on how to run others' projects on my computer? 
Do I fork them? I don't think I saw any specific instructions on how we should do that. I want to check out some of the projects so to give them feedback. Thanks in advance!

**Comment by BobbyGatlin** [comment]
@elicegreen I played your game and it was pretty cool. Took a long time to finish but worked just fine. I was able to get your game by cloning your repository.

**Comment by chrispelaez** [comment]
In order to get yours to work I selected the option to open your files in the github desktop. From there I was able to open your files. Other projects I have played around with I was able to copy and paste the code into the python shell and ran them with no problem. Most of all read the read me for each project to see the different conditions for running each program.

**Comment by elicegreen** [comment]
Thanks @BobbyGatlin and @chrispelaez!
I'll be home soon and will check out some projects. Now that I know how to. 
Glad you enjoyed the game! :-)

**Comment by halfaro1** [comment]
@elicegreen love this! ✨ all around. The only thing that's missing is a design document that explains the logic behind your code. Much of this work was done in your issue so you don't have to reinvent the wheel.

Adding a link to your proposal so that when we close this pull request it closes #9

**Comment by elisenharper** [comment]
Very well done! It ran without any problems on my computer

**Comment by halfaro1** [comment]
@elicegreen I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
