### PR TITLE
The Bank. Final Project.

### PR DESCRIPTION
**Pull request by JoshuaRi**
Is there any more features I should implement?

### CODE REVIEW

**Comment by halfaro1** [comment]
Good start, @JoshuaRi. I would recommend you print some possible actions on the screen for the user. Although we can see your instructions in the `README` file, a person running your program wouldn't know what to do. Additionally, there should be some extra information on the screen about who some of the calculations are performed. Give the user more information rather than less. 

Your program should use functions as it's been a best practice for all projects up to now.

I also see duplicated code on the root directory and also in the `devel` folder. Keep your code in the `devel` folder and remove duplicates from the root directory.

You'll also need a design document that explains the logic behind your code.

**Comment by Nate388** [comment]
@JoshuaRi. I really love the concept of this game. I would like it if the instructions could print again after every turn so that way I know what the inputs are each turn. Overall I really liked playing this. Good Job! :sparkles:

**Comment by aeuteneuer** [comment]
Joshua, 

I will have to agree with Nate.  This would be really good if it could print after every turn to notify the user that something is happening. Other than that great job!

**Comment by JoshuaRi** [comment]
Thank you, so I should make the program print what has happened exactly when someone wins/loses a investment?

**Comment by halfaro1** [comment]
@JoshuaRi I think that would be a good idea. I'm also not seeing that design document yet. Just wanted to make sure that you're aware before the deadline tonight.

**Comment by JoshuaRi** [comment]
I thought I put the logic to my code inside of the code itself.

**Comment by halfaro1** [comment]
@JoshuaRi I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
