### PR TITLE
my project

### PR DESCRIPTION
**Pull request by shuroq**

### CODE REVIEW

**Comment by cholbrook2** [comment]
This is really cool! The only thing I would change is the first question of "What is the cost" to have at least a space after it, because otherwise you are typing right next to the question.

**Comment by ryby6969** [comment]
This is pretty neat. The only thing that I would like is to be able to keep going until I want to end it myself.

**Comment by digitalBeast** [comment]
Ayee thats awesome, done pretty good job at this one keep it up!

**Comment by shuroq** [comment]
@halfaro1 what do you think professor? is it good ?

**Comment by halfaro1** [comment]
Thanks @shuroq! Great start!

I have a few suggestions. I entered a total cost of $20 and cash tendered of $25 and it calculated four $1 bills. It should have calculated either one $5 or or five $1 bills, right?

Additionally, good start on your design document, but modify it a little bit so it talks about the magic behind the scenes, how is your program structured and how does it work?

Finally, and this is the most important, please utilize functions as part of your program. It's a feature we learned about and used all semester.

Linking this pull request to your proposal so it closes #21

**Comment by shuroq** [comment]
screen shot 2016-04-24 at 3 53 42 am
@halfaro1Thank you for your feedback. I ran the code and it gave me 5 one dollar bills. Also, I made a new updated code and I add the tax deduction. I attach a screenshot of my code showing the 5 one dollar bills.

**Comment by shuroq** [comment]
@halfaro1 
screen shot 2016-04-26 at 8 09 14 pm
Thank you for your feedback. I ran the code and it gave me 5 one dollar bills. Also, I made a new updated code and I add the tax deduction. I attach a screenshot of my code showing the 5 one dollar bills.

**Comment by halfaro1** [comment]
@shuroq I see! How is tax calculated?

**Comment by shuroq** [comment]
@halfaro1 this is how I calculated tax
 tax= float (cost*.09)

**Comment by shuroq** [comment]
@halfaro1 this is how I calculated tax
tax= round (cost*.05)

**Comment by halfaro1** [comment]
@shuroq great work on the design. If you want to reach for the 🌠 please segment your code into functions.

**Comment by shuroq** [comment]
@halfaro1 sure professor, I will do it

**Comment by halfaro1** [comment]
@shuroq I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
