### PR TITLE
Tile

### PR DESCRIPTION
**Pull request by ngocnguyen83**
You just need to download my code and run it :yum: :sparkles:

### CODE REVIEW

**Comment by ngocnguyen83** [comment]
@halfaro1

**Comment by sabbott7** [comment]
Yes I liked it,Defniitey the one-stop shop for my conversion needs !

**Comment by cholbrook2** [comment]
Wow this has quite a bit of depth to it! I can tell that this is something that you really thought about. I did just want to say that when I try to run the program regularly, it shuts down before I can read the output. Using Python to run it, though, it's perfectly fine.

**Comment by chrispelaez** [comment]
Very creative use of the calculator function. Its funny in a way. When I look at your code all i can think of is the fact that with a few changes you could have the code convert recipes for use in large production kitchens like mass production bakeries.

**Comment by jashhhhhhh** [comment]
Love the complexity of this program and how it simplifies an extensive arithmetic process into a simple input based algorithm. I am sure this kind of program would be incredibly useful and time saving for tile sales people!!

**Comment by halfaro1** [comment]
@ngocnguyen83 awesome program. Might I suggest you use functions to show the best practice of what we've used throughout the semester? Another suggestion would be to make the cost rounded to 2 decimal places, as money is always read to the nearest cent.

Also, regarding your README, to be consistent with what the other classmates are doing, please include instructions about how to get your program running in that file. 

Overall great work especially with your design document.

Linking this pull request so that it close issue #39

**Comment by ngocnguyen83** [comment]
Thank you professor @halfaro1   :smile:
I edited my codes by using functions and also rounded the cost to two decimal places :sparkles:

**Comment by halfaro1** [comment]
@ngocnguyen83 fantastic work! 👍  Your grade is on Blackboard.

**Pull request closed without merging**
