### PR TITLE
Final Project 1st run

### PR DESCRIPTION
**Pull request by ukates**
Please any feedback would be helpful! I am looking to add a few more things to the program when it comes to creating .txt file and saving results to a folder... but I will be looking into that possibly tomorrow.  

For now, I would love to know if this is working for you as it is for me!

### CODE REVIEW

**Comment by elicegreen** [comment]
@ukates I really like your program! Ran it a couple of times and it worked well.
I love the time suspension method! I didn't know you could do that. It would be a great addition to my program (card game war). I'm actually going to add it to my code. Thanks!

**Comment by ukates** [comment]
@elicegreen I know ! I know it isn't necessary but I feel like it flows better instead of just throwing all the text at the user at once!

**Comment by elicegreen** [comment]
I agree. It makes the program much more user-friendly!

**Comment by jashhhhhhh** [comment]
This program runs smooth and could be very useful! Thanks for your great work!

**Comment by ukates** [comment]
Current version will create a folder under current working directory titled LoanDetails, it will then create .txt file with all of the payoff details calculated from the program and save it into that folder.  The program will overwrite the old file each time it is run.  I also added some text to the program that just tells the user that it is creating a new folder, and creating a new file to save to that folder, not really needed but i thought it was cool.

**Comment by shuroq** [comment]
I ran your code and it is working smoothly congrats!! Great project and useful idea. Good luck

**Comment by halfaro1** [comment]
@ukates awesome work. I like how your program uses functions and is very user friendly and even creates a file. Great work so far. Make sure you add a design document as that's required for credit. Additionally some comments wouldn't help. Fantastic work improving on your program over time, too! ✨ 

Linking to your proposal so it closes #44

**Comment by larawillson** [comment]
This was so easy to use and can be so useful! You did a great job with the very specific prompts, and it really easily walked the user through the entire program. Congrats this is great!

**Comment by ukates** [comment]
@halfaro1 I did add some comments and a design document, please let me know if i should add anything!

**Comment by halfaro1** [comment]
@ukates I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
