### PR TITLE
F1 Quiz Final

### PR DESCRIPTION
**Pull request by imiller6**
F1 Quiz for final  project.

### CODE REVIEW

**Comment by DanielCowman** [comment]
I got a 50%, looks like I failed. 👍 Nice quiz, worked flawlessly for me, good job!

**Comment by digitalBeast** [comment]
That is impressive, I like it. just by looking at the program I can tell how it works. I having some difficulties on downloading your program, but I think the only little  mistake you made was the correction points. noticed how when someone gets it right they get a point. So when they get it wrong they still get a point. So I'm not entirely sure because I haven't tried to play the quiz myself. but its good tho

**Comment by halfaro1** [comment]
@imiller6 awesome work so far. I have two suggestions:
1. Use functions as they've been something you've seen in projects throughout the semester.
2. Add a design document explaining the structure and logic of your code.

**Comment by halfaro1** [comment]
@imiller6 I also noticed your proposal is still open. Please finalize that before moving forward.

**Comment by halfaro1** [comment]
@imiller6 You received this score because your proposal was either (a) submitted late, and/or (b) you did not respond to feedback of your proposal in time to get approval before the due date.

**Pull request closed without merging**
