### PR TITLE
Connect four

### PR DESCRIPTION
**Pull request by BranLWill**

### CODE REVIEW

**Comment by halfaro1** [comment]
@BranLWill awesome start! Please don't forget to include a design document that explains how your code works. Also, what would you like feedback on from myself and your classmates?

I'm linking to your proposal so that when we close this pull request it will also close #23

**Comment by BranLWill** [comment]
@halfaro1 Well the first pull request was not my actual final. This pull request is my real final and i am having trouble with getting the users input to drop down in the board, so right now it is just one big tic-tac-toe game. So any suggestions on how to go about this would be helpful.

**Comment by halfaro1** [comment]
@BranLWill alright that's all part of design. For tic-tac-toe we used a dictionary, I'm not seeing that on your code.

Also some housekeeping, the `README` file is supposed to tell your classmates how to open and run your code. Your code should like in its one `.py` file.

**Comment by BranLWill** [comment]
@halfaro1 There is the runner file to play it and the design file like you asked with the instructions fixed up. I just don't know of any other way to start up the files to play them.

**Comment by halfaro1** [comment]
@BranLWill I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
