### PR TITLE
PsychicPC-V1

### PR DESCRIPTION
**Pull request by xyngabo**

### CODE REVIEW

**Comment by xyngabo** [comment]
Feature List (to be added):
        Psychic mode - guesses first time every time
        Random mode - picks random number higher or lower but random
        Saving - create a  txt file and keep track of how many times the program succeeded

Easter Egg

**Comment by halfaro1** [comment]
@xyngabo just wanted to let you know not to pay attention to the automated tests for this one. I forgot to turn it off since everyone's final project will be different. As long as it works locally and you include instructions on how to get it to work for everyone else, you're good to go. When you're ready for us to look it over, just tell us in a comment via this pull request and don't forget to @ mention me as well

**Comment by halfaro1** [comment]
Great progress, by the way 🌈

**Comment by sabbott7** [comment]
I liked your concept of a psychic computer, very sci-fi indeed !

**Comment by xyngabo** [comment]
@halfaro1 I am ready for my project to be looked over.

**Comment by xyngabo** [comment]
@halfaro1 I am ready for my project to be looked over.

**Comment by xyngabo** [comment]
The program likely will not work for an hour or two.  I switched my name servers so that cloudflare would cache my site, but their method seems to be breaking the JavaScript portion of this, so I have switched my name servers back to point directly at my VPS.

**Comment by ngocnguyen83** [comment]
:yum: works smoothly in my computer and very fun to play. Your instruction is clear to follow :thumbsup:

**Comment by smoussadeq** [comment]
Worked well on my computer. Great work! There is nothing I think you should add or modify.

**Comment by jashhhhhhh** [comment]
This is such an interesting concept! This kind of thought process is how we can progress and simplify technology with simple programming

**Comment by halfaro1** [comment]
@xyngabo awesome! I do have some suggestions, mostly in terms of documentation. Your documentation should explain some things, such as the need for the Selenium package and Firefox. Additionally, the documentation should probably explain what the 3 modes (Standard, Random, and Psychic do). Programming wise, everything looks 👍

**Comment by halfaro1** [comment]
I'm also linking this to your issues so that when you finish this it closes #3

**Comment by halfaro1** [comment]
@xyngabo I also forgot to mention the design document - do you have one?

**Comment by JoshuaRi** [comment]
Works great on my computer, the instructions are easy to follow. I don't think you need to add or modify anything else.

**Comment by imiller6** [comment]
Works great on my end. I also liked how clear and intuitive the instructions were to follow.

**Comment by xyngabo** [comment]
@ halfaro1  The explanation of the modes is on the webpage.  I can put it in the read me file too.

**Comment by halfaro1** [comment]
Fantastic work, @xyngabo 
Your grade is now in Blackboard 👍

**Pull request closed without merging**
