### PR TITLE
Josh McKnight final 

### PR DESCRIPTION
**Pull request by jashhhhhhh**
This is the rough draft and I feel like I need to add more, any suggestions?

### CODE REVIEW

**Comment by jashhhhhhh** [comment]
@halfaro1 rough outline^ ; also thinking to maybe add a verification function to ensure the user inputs a valid email, or at least a valid email address format (i.e. "whatever@emailservice.com") .
thoughts?

**Comment by halfaro1** [comment]
@jashhhhhhh is the right file `.py` or `.py.txt`? There should only be one working file to minimize confusion. Additionally, please add your instructions to the `README` in the `devel` directory so your classmates know how to run your code. 

Your code should be using functions as they have been a required component of most of the semester.

Finally, please don't forget to include a design document explaining the logic behind your code.

Linking to your proposal so it closes #32

**Comment by jashhhhhhh** [comment]
@halfaro1 thanks for the feedback! updated the files. I noticed after some more testing that the program will overwrite any information if the file already exists. Will work on the file writing function

**Comment by halfaro1** [comment]
@jashhhhhhh great! Thanks for taking the feedback. Could you give us a little information in the design document about how you perform each of the steps you described? I'm sure regex's were difficult for your classmates so they'd appreciate an explanation.

**Comment by halfaro1** [comment]
@jashhhhhhh I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
