### PR TITLE
Web Search and Instagram Screenshot

### PR DESCRIPTION
**Pull request by elisenharper**

### CODE REVIEW

**Comment by halfaro1** [comment]
@elisenharper pretty cool stuff! Please make sure you use functions and include a design document that explains the structure and logic behind your program. 

Linking to your proposal so it closes #8

**Comment by elisenharper** [comment]
I'm curious to hear how this works on other computers! Any feedback would be helpful!

**Comment by chrispelaez** [comment]
@elisenharper Your program seems to be working on my end If possible could you try and see if mine is working I was having issues the last hour trying to get the programs to show up.

**Comment by elisenharper** [comment]
Thank you for the feedback @chrispelaez! Glad to hear it ran smoothly. You never know when the Internet is involved! I'll check yours out

**Comment by halfaro1** [comment]
@elisenharper ❤️ the design document. If you're reaching for the 🌠 ensure you use functions.

**Comment by ukates** [comment]
@elisenharper this program is so cool, when I ran it it worked very smoothly.  The design document is so detailed, it was really helpful to learn how you do it and the reason you program was made the way it was.  I love how the time module was used to help pause the program to allow time for loading... really smart! Great project!

**Comment by halfaro1** [comment]
@elisenharper I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Pull request closed without merging**
